development:
  adapter: postgresql
  database: g2_advertising_development
  host: localhost
  username: adamgamble
  password: ee6296yp

test: &test
  adapter: postgresql
  database: g2_advertising_test
  host: localhost
  username: adamgamble
  password: ee6295yp

cucumber:
  <<: *test